// This file was auto-generated by material_compiler.c.

typedef union Shader_Parameters {
	struct {
		M4 local_to_world_space;
	} rusted_iron;
} Shader_Parameters;

typedef struct Render_Material {
	GPU_Shader_ID material; // @TODO: This should be a material id.
	s32 count;
	Shader_Parameters parameters;
} Render_Material;

