// This file was auto-generated by material_compiler.c.

typedef struct Rusted_Iron_Vertex_Bind_Per_Material_Update_Delayed {
	V4 color;
} Rusted_Iron_Vertex_Bind_Per_Material_Update_Delayed;

typedef struct Rusted_Iron_Vertex_Bind_Per_Object_Update_Immediate {
	M4 model_to_world_space;
} Rusted_Iron_Vertex_Bind_Per_Object_Update_Immediate;

typedef union Descriptor_Set_Parameters  {
	struct {
		Rusted_Iron_Vertex_Bind_Per_Material_Update_Delayed vertex_bind_per_material_update_delayed;
		Rusted_Iron_Vertex_Bind_Per_Object_Update_Immediate vertex_bind_per_object_update_immediate;
	} rusted_iron;
} Descriptor_Set_Parameters;

typedef struct Descriptor_Set_Data  {
	GPU_Shader_ID shader_id;
	s32 count;
	Descriptor_Set_Parameters parameters;
} Descriptor_Set_Data;

