// This file was generated by the preprocessor.

typedef struct {
	V4 color;
	M4 model_view_projection;
} Flat_Color_UBO;

#define FLAT_COLOR_UBO_DESCRIPTOR_SET_NUMBER 0
#define FLAT_COLOR_UBO_BINDING_NUMBER 0

typedef struct {
	V4 fragment_color;
} Flat_Color_Push_Constants;

#define FLAT_COLOR_DESCRIPTOR_SET_TYPE_COUNT 1

