// This file was auto-generated by material_compiler.c.

typedef enum GPU_Shader_ID {
	RUSTED_IRON_SHADER,

	SHADER_COUNT,
} GPU_Shader_ID;

typedef enum GPU_Shader_Stage {
	VERTEX_SHADER_STAGE,
	FRAGMENT_SHADER_STAGE,
	SHADER_STAGE_COUNT,
} GPU_Shader_Stage;

typedef struct GPU_Shader {
	s32 module_count;
	VkShaderModule modules[SHADER_STAGE_COUNT];
} GPU_Shader;

typedef enum GPU_Descriptor_Set_ID {
} GPU_Descriptor_Set_ID;


typedef struct Descriptor_Set_Layouts {
	VkDescriptorSetLayout rusted_iron[RUSTED_IRON_DESCRIPTOR_SET_COUNT];
} Descriptor_Set_Layouts;

