// This file was auto-generated by material_compiler.c.

const char *SHADER_SPIRV_FILEPATHS[SHADER_COUNT][SHADER_STAGE_COUNT] = {
	[RUSTED_IRON_SHADER][VERTEX_SHADER_STAGE] = "build/shaders/binaries/rusted_iron_vert.spirv",
	[RUSTED_IRON_SHADER][FRAGMENT_SHADER_STAGE] = "build/shaders/binaries/rusted_iron_frag.spirv",
};

void Render_API_Load_Shaders(Render_API_Context *context, GPU_Shader shaders[SHADER_COUNT]) {
	for (s32 i = 0; i < SHADER_COUNT; i++) {
		for (s32 j = 0; j < SHADER_STAGE_COUNT; j++) {
			if (!SHADER_SPIRV_FILEPATHS[i][j]) {
				continue;
			}
			Read_File_Result spirv = Read_Entire_File(SHADER_SPIRV_FILEPATHS[i][j]);
			Assert(spirv.data);
			VkShaderModuleCreateInfo shader_module_create_info = {
				.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
				.codeSize = spirv.size,
				.pCode = (u32 *)spirv.data,
			};
			VK_CHECK(vkCreateShaderModule(context->device, &shader_module_create_info, NULL, &shaders[i].modules[shaders[i].module_count++]));
		}
	}
}

void Render_API_Create_Descriptor_Sets(Render_API_Context *context) {
}

