#define GLOBAL_DESCRIPTOR_SET_INDEX 0
#define VIEW_DESCRIPTOR_SET_INDEX 1
#define MATERIAL_DESCRIPTOR_SET_INDEX 2
#define OBJECT_DESCRIPTOR_SET_INDEX 3
#define DESCRIPTOR_SET_COUNT 4

#define FLAT_SHADING_MODEL 0
#define PHONG_SHADING_MODEL 1
#define PBR_SHADING_MODEL 2
