// This file was auto-generated by material_compiler.c.

struct ShaderStageFilepath {
	GPU_Shader_Stage id;
	String path;
};

Array<Array<ShaderStageFilepath>> shaderFilepaths = CreateInitializedArray(
	CreateInitializedArray(
		ShaderStageFilepath{
			.id = GPU_VERTEX_SHADER_STAGE,
			.path = "build/shaders/binaries/rusted_iron_vert.spirv",
		},
		ShaderStageFilepath{
			.id = GPU_FRAGMENT_SHADER_STAGE,
			.path = "build/shaders/binaries/rusted_iron_frag.spirv",
		}
	)
);

struct {
	VkDescriptorType type;
	s32 non_immediate_descriptor_count;
	s32 immediate_descriptor_count;
} vulkan_descriptor_pool_size_infos[] = {
	{
		.type = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
		.non_immediate_descriptor_count = 1,
		.immediate_descriptor_count = 1,
	},
};

void Render_API_Load_Shaders(Render_API_Context *context, GPU_Shader shaders[GPU_SHADER_COUNT]) {
	for (s32 i = 0; i < GPU_SHADER_COUNT; i++) {
		for (auto const &stage : shaderFilepaths[i]) {
			auto [spirv, error] = ReadEntireFile(stage.path);
			Assert(!error);
			VkShaderModuleCreateInfo shaderModuleCreateInfo = {
				.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
				.codeSize = Length(spirv),
				.pCode = (u32 *)&spirv[0],
			};
			shaders[i].stages[shaders[i].stage_count] = stage.id;
			VK_CHECK(vkCreateShaderModule(context->device, &shaderModuleCreateInfo, NULL, &shaders[i].modules[shaders[i].stage_count]));
			shaders[i].stage_count++;
		}
	}
}

void Vulkan_Create_Descriptor_Set_Layouts(Render_API_Context *context, u32 swapchain_image_count, VkDescriptorSetLayout *layouts) {
	{
		VkDescriptorSetLayoutBinding bindings[] = {
			{
				.binding = 0,
				.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
				.descriptorCount = 1,
				.stageFlags = VK_SHADER_STAGE_VERTEX_BIT,
				.pImmutableSamplers = NULL,
			},
		};
		VkDescriptorSetLayoutCreateInfo descriptor_set_layout_create_info = {
			.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
			.flags = VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT,
			.bindingCount = ArrayCount(bindings),
			.pBindings = bindings,
		};
		VK_CHECK(vkCreateDescriptorSetLayout(context->device, &descriptor_set_layout_create_info, NULL, &layouts[0]));
	}
	{
		VkDescriptorSetLayoutBinding bindings[] = {
			{
				.binding = 0,
				.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
				.descriptorCount = 1,
				.stageFlags = VK_SHADER_STAGE_VERTEX_BIT,
				.pImmutableSamplers = NULL,
			},
		};
		VkDescriptorSetLayoutCreateInfo descriptor_set_layout_create_info = {
			.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
			.flags = VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT,
			.bindingCount = ArrayCount(bindings),
			.pBindings = bindings,
		};
		VK_CHECK(vkCreateDescriptorSetLayout(context->device, &descriptor_set_layout_create_info, NULL, &layouts[1]));
	}
}

