// This file was auto-generated by material_compiler.c.

enum GPU_Shader_Stage {
	GPU_VERTEX_SHADER_STAGE = VK_SHADER_STAGE_VERTEX_BIT,
	GPU_FRAGMENT_SHADER_STAGE = VK_SHADER_STAGE_FRAGMENT_BIT,

	GPU_SHADER_STAGE_COUNT
};

typedef enum GPU_Shader_ID {
	RUSTED_IRON_SHADER,

	GPU_SHADER_COUNT,
} GPU_Shader_ID;

typedef struct GPU_Shader {
	s32 stage_count;
	GPU_Shader_Stage stages[GPU_SHADER_STAGE_COUNT];
	VkShaderModule modules[GPU_SHADER_STAGE_COUNT];
} GPU_Shader;

typedef enum GPU_Descriptor_Set_ID {
	RUSTED_IRON_VERTEX_BIND_PER_MATERIAL_UPDATE_DELAYED_DESCRIPTOR_SET,
	RUSTED_IRON_VERTEX_BIND_PER_OBJECT_UPDATE_IMMEDIATE_DESCRIPTOR_SET,
GPU_DESCRIPTOR_SET_LAYOUT_COUNT

} GPU_Descriptor_Set_ID;

#define RUSTED_IRON_DESCRIPTOR_SET_LAYOUT_COUNT 2

struct GPU_Shader_Descriptor_Sets {
	GPU_Buffer buffer;
	s32 buffer_offset;
	s32 set_count;
	GPU_Descriptor_Set *sets;
};

enum GPU_Descriptor_ID {
	COLOR_DESCRIPTOR,
	MODEL_TO_WORLD_SPACE_DESCRIPTOR,
};

union GPU_Descriptor_Data {
	f32 v4[4];
	f32 m4[4][4];
};

struct GPU_Descriptor_Update_Info {
	GPU_Descriptor_ID id;
	GPU_Descriptor_Data data;
};

#define GPU_NON_IMMEDIATE_DESCRIPTOR_COUNT 1
#define GPU_IMMEDIATE_DESCRIPTOR_COUNT 1
